# fly.toml app configuration file for a background worker

app = 'script-bold-waterfall-5340'
primary_region = 'cdg'

# This tells Fly to run the CMD from the Dockerfile as a background 'app' process
# and to keep it running.
[processes]
  app = ''

# This configures the virtual machine
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# This configures the persistent storage
[mounts]
  source = "data"
  destination = "/data"