# fly.toml app configuration file generated for script-bold-waterfall-5340 on 2025-06-14T17:21:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'script-bold-waterfall-5340'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
[mounts]
  source="data"
  destination="/data"